package com.holo.framework.horm.core.dialect;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

public class H2Dialect implements Dialect {

    private final String mode;

    public H2Dialect(String mode) {
        this.mode = Objects.requireNonNull(mode, "mode must not be null");
    }

    @Override
    public String name() {
        if (isPostgresqlMode()) {
            return "h2-postgresql";
        }
        return "h2";
    }

    /**
     * Returns {@code true} when this H2 dialect is configured for PostgreSQL
     * compatibility mode.
     */
    public boolean isPostgresqlMode() {
        return "postgresql".equalsIgnoreCase(mode);
    }

    @Override
    public void paginate(StringBuilder sql, List<Object> bindings, long offset, long limit) {
        sql.append(" LIMIT ?");
        bindings.add(limit);
        if (offset > 0) {
            sql.append(" OFFSET ?");
            bindings.add(offset);
        }
    }

    @Override
    public String identityColumn() {
        if ("postgresql".equalsIgnoreCase(mode)) {
            return "BIGINT GENERATED BY DEFAULT AS IDENTITY";
        }
        return "BIGINT AUTO_INCREMENT";
    }

    @Override
    public IdentityStrategy identityStrategy() {
        return IdentityStrategy.IDENTITY;
    }

    @Override
    public char identifierQuoteChar() {
        if ("postgresql".equalsIgnoreCase(mode)) {
            return '"';
        }
        return '`';
    }

    @Override
    public String sqlType(Class<?> javaType) {
        if (javaType == String.class) return "VARCHAR(255)";
        if (javaType == Integer.class || javaType == int.class) return "INT";
        if (javaType == Long.class || javaType == long.class) return "BIGINT";
        if (javaType == BigDecimal.class) return "DECIMAL(19,2)";
        if (javaType == Boolean.class || javaType == boolean.class) return booleanType();
        if (javaType == Instant.class) return timestampType();
        if (javaType == byte[].class) return "BLOB";
        return "VARCHAR(255)";
    }

    @Override
    public boolean supportsUpsert() {
        return true;
    }

    @Override
    public String upsert(String table, String[] columns, String[] uniqueColumns, String[] updateColumns) {
        var sj = new StringJoiner(", ");
        for (var col : columns) sj.add(quoteIdentifier(col));
        var insertCols = sj.toString();

        sj = new StringJoiner(", ");
        for (var ignored : columns) sj.add("?");
        var placeholders = sj.toString();

        if ("postgresql".equalsIgnoreCase(mode)) {
            var uniqueJoin = new StringJoiner(", ");
            for (var col : uniqueColumns) uniqueJoin.add(quoteIdentifier(col));
            var updateClause = new StringJoiner(", ");
            for (var col : updateColumns) {
                updateClause.add(quoteIdentifier(col) + "=EXCLUDED." + quoteIdentifier(col));
            }
            return "INSERT INTO " + quoteIdentifier(table)
                + " (" + insertCols + ") VALUES (" + placeholders + ")"
                + " ON CONFLICT (" + uniqueJoin + ") DO UPDATE SET " + updateClause;
        }

        var updateClause = new StringJoiner(", ");
        for (var col : updateColumns) {
            updateClause.add(quoteIdentifier(col) + "=VALUES(" + quoteIdentifier(col) + ")");
        }
        return "INSERT INTO " + quoteIdentifier(table)
            + " (" + insertCols + ") VALUES (" + placeholders + ")"
            + " ON DUPLICATE KEY UPDATE " + updateClause;
    }

    @Override
    public boolean supportsBatchInsertValues() {
        return true;
    }

    @Override
    public String dropIndex(String indexName, String tableName) {
        if ("postgresql".equalsIgnoreCase(mode)) {
            return "DROP INDEX " + quoteIdentifier(indexName);
        }
        return "DROP INDEX " + quoteIdentifier(indexName) + " ON " + quoteIdentifier(tableName);
    }

    @Override
    public String renameTable(String oldName, String newName) {
        if ("postgresql".equalsIgnoreCase(mode)) {
            return "ALTER TABLE " + quoteIdentifier(oldName) + " RENAME TO " + quoteIdentifier(newName);
        }
        return "RENAME TABLE " + quoteIdentifier(oldName) + " TO " + quoteIdentifier(newName);
    }

    @Override
    public String booleanType() {
        if ("postgresql".equalsIgnoreCase(mode)) {
            return "BOOLEAN";
        }
        return "TINYINT(1)";
    }

    @Override
    public String timestampType() {
        if ("postgresql".equalsIgnoreCase(mode)) {
            return "TIMESTAMP";
        }
        return "DATETIME(6)";
    }
}
