package com.holo.framework.horm.meta;

import com.holo.framework.horm.meta.annotation.Isolation;
import com.holo.framework.horm.meta.annotation.Propagation;

/**
 * Immutable metadata describing a transactional method, generated by the
 * APT processor from {@link com.holo.framework.horm.meta.annotation.Transactional}
 * annotations.
 */
public final class TransactionMethodMeta {

    private final String methodName;
    private final Propagation propagation;
    private final Isolation isolation;
    private final int timeout;
    private final boolean readOnly;

    public TransactionMethodMeta(String methodName, Propagation propagation,
                                 Isolation isolation, int timeout, boolean readOnly) {
        this.methodName = methodName;
        this.propagation = propagation;
        this.isolation = isolation;
        this.timeout = timeout;
        this.readOnly = readOnly;
    }

    public String methodName() { return methodName; }
    public Propagation propagation() { return propagation; }
    public Isolation isolation() { return isolation; }
    public int timeout() { return timeout; }
    public boolean readOnly() { return readOnly; }

    @Override
    public String toString() {
        return "TransactionMethodMeta{" + methodName + ", " + propagation + ", "
            + isolation + ", timeout=" + timeout + ", readOnly=" + readOnly + "}";
    }
}
