package com.holo.framework.horm.meta;

import com.holo.framework.horm.meta.annotation.Isolation;
import com.holo.framework.horm.meta.annotation.Propagation;

import java.util.List;

/**
 * Immutable metadata describing a transactional method, generated by the
 * APT processor from {@link com.holo.framework.horm.meta.annotation.Transactional}
 * annotations.
 */
public final class TransactionMethodMeta {

    private final String methodName;
    private final Propagation propagation;
    private final Isolation isolation;
    private final int timeout;
    private final boolean readOnly;
    private final List<String> rollbackFor;
    private final List<String> noRollbackFor;

    public TransactionMethodMeta(String methodName, Propagation propagation,
                                 Isolation isolation, int timeout, boolean readOnly) {
        this(methodName, propagation, isolation, timeout, readOnly, List.of(), List.of());
    }

    public TransactionMethodMeta(String methodName, Propagation propagation,
                                 Isolation isolation, int timeout, boolean readOnly,
                                 List<String> rollbackFor, List<String> noRollbackFor) {
        this.methodName = methodName;
        this.propagation = propagation;
        this.isolation = isolation;
        this.timeout = timeout;
        this.readOnly = readOnly;
        this.rollbackFor = rollbackFor;
        this.noRollbackFor = noRollbackFor;
    }

    public String methodName() { return methodName; }
    public Propagation propagation() { return propagation; }
    public Isolation isolation() { return isolation; }
    public int timeout() { return timeout; }
    public boolean readOnly() { return readOnly; }
    public List<String> rollbackFor() { return rollbackFor; }
    public List<String> noRollbackFor() { return noRollbackFor; }

    /**
     * Determines whether the given exception should trigger a rollback
     * according to the rollback rules declared on this method.
     *
     * <p>Evaluation rules:
     * <ul>
     *   <li>If {@code noRollbackFor} contains the exception class name (or a
     *       superclass), the exception never triggers rollback.</li>
     *   <li>If {@code rollbackFor} is non-empty, only exceptions whose class
     *       name (or a superclass) appears in the list trigger rollback.</li>
     *   <li>Otherwise, {@link RuntimeException} (and subclasses) trigger
     *       rollback by default.</li>
     * </ul>
     *
     * @param throwable the exception to evaluate
     * @return {@code true} if the transaction should be rolled back
     */
    public boolean shouldRollback(Throwable throwable) {
        if (throwable == null) {
            return false;
        }
        String exClassName = throwable.getClass().getName();

        // noRollbackFor takes precedence
        if (!noRollbackFor.isEmpty() && matchesAny(exClassName, noRollbackFor)) {
            return false;
        }

        // explicit rollbackFor list
        if (!rollbackFor.isEmpty()) {
            return matchesAny(exClassName, rollbackFor);
        }

        // default: RuntimeException and its subclasses trigger rollback
        return throwable instanceof RuntimeException;
    }

    private static boolean matchesAny(String exClassName, List<String> candidates) {
        for (String candidate : candidates) {
            if (exClassName.equals(candidate)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String toString() {
        return "TransactionMethodMeta{" + methodName + ", " + propagation + ", "
            + isolation + ", timeout=" + timeout + ", readOnly=" + readOnly
            + ", rollbackFor=" + rollbackFor + ", noRollbackFor=" + noRollbackFor + "}";
    }
}
